export const multas = [
  {
    "codigomulta": "M001",
    "motivomulta": "Excesso de Velocidade",
    "nomecondutor": "João Silva",
    "matriculacondutor": "12345",
    "gravidademulta": "Média",
    "datamulta": "2023-10-28",
    "localizacao": "Rua Principal, Cidade A",
    "placaveiculo": "ABC123D",
  },
  {
    "codigomulta": "M002",
    "motivomulta": "Estacionamento Irregular",
    "nomecondutor": "Maria Souza",
    "matriculacondutor": "54321",
    "gravidademulta": "Leve",
    "datamulta": "2023-10-29",
    "localizacao": "Avenida Central, Cidade B",
    "placaveiculo": "XYZ456E",
  },
  {
    "codigomulta": "M003",
    "motivomulta": "Ultrapassagem Proibida",
    "nomecondutor": "Pedro Santos",
    "matriculacondutor": "98765",
    "gravidademulta": "Grave",
    "datamulta": "2023-10-30",
    "localizacao": "Rodovia X, Cidade C",
    "placaveiculo": "LMN789F",
  },
  {
    "codigomulta": "M004",
    "motivomulta": "Sem Cinto de Segurança",
    "nomecondutor": "Ana Rodrigues",
    "matriculacondutor": "67890",
    "gravidademulta": "Grave",
    "datamulta": "2023-10-31",
    "localizacao": "Rua Secundária, Cidade A",
    "placaveiculo": "PQR012G",
  },
  {
    "codigomulta": "M005",
    "motivomulta": "Sem Inspeção Veicular",
    "nomecondutor": "Carlos Fernandes",
    "matriculacondutor": "34567",
    "gravidademulta": "Leve",
    "datamulta": "2023-11-01",
    "localizacao": "Avenida Norte, Cidade B",
    "placaveiculo": "UVW345H",
  },
  {
    "codigomulta": "M006",
    "motivomulta": "Atravessar Sinal Vermelho",
    "nomecondutor": "Sofia Lima",
    "matriculacondutor": "23456",
    "gravidademulta": "Grave",
    "datamulta": "2023-11-02",
    "localizacao": "Rodovia Y, Cidade C",
    "placaveiculo": "JKL678I",
  },
  {
    "codigomulta": "M007",
    "motivomulta": "Estacionamento em Local Proibido",
    "nomecondutor": "Luiz Mendes",
    "matriculacondutor": "76543",
    "gravidademulta": "Leve",
    "datamulta": "2023-11-03",
    "localizacao": "Rua Principal, Cidade A",
    "placaveiculo": "DEF901J",
  },
  {
    "codigomulta": "M008",
    "motivomulta": "Dirigir Sob Efeito de Álcool",
    "nomecondutor": "Laura Oliveira",
    "matriculacondutor": "45678",
    "gravidademulta": "Grave",
    "datamulta": "2023-11-04",
    "localizacao": "Avenida Central, Cidade B",
    "placaveiculo": "GHI234K",
  },
  {
    "codigomulta": "M009",
    "motivomulta": "Ultrapassagem em Local Não Permitido",
    "nomecondutor": "Miguel Pereira",
    "matriculacondutor": "54321",
    "gravidademulta": "Grave",
    "datamulta": "2023-11-05",
    "localizacao": "Rodovia X, Cidade C",
    "placaveiculo": "MNO567L",
  },
  {
    "codigomulta": "M010",
    "motivomulta": "Uso de Celular ao Volante",
    "nomecondutor": "Isabel Santos",
    "matriculacondutor": "87654",
    "gravidademulta": "Média",
    "datamulta": "2023-11-06",
    "localizacao": "Rua Secundária, Cidade A",
    "placaveiculo": "STU890M",
  },
];
